### ISSUE TITLE
Please include original image, downsamples image and reconstructed image in the README.

### ISSUE THREAD

**Issue by anilgulecha** [alexjc/neural-enhance#1]
Re: https://news.ycombinator.com/item?id=12822960

This will help to see the difference between real and the reconstructed image as well.

**Comment by alexjc** [comment]
For the Old Station, Hong Kong and the Bank Lobby, the original image is linked just below the preview GIF. You can also download the HD versions in the preview tool.

I don't want to clutter the README too much. Interested users will soon be able to do it for themselves using simple Docker install.
