### ISSUE TITLE
Docker from the command line doesn't work on an image

### ISSUE THREAD

**Issue by gducharme** [alexjc/neural-enhance#101]
I'm following the Docker installation flow
```docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance merc1.jpg```

And that image is local to where this command is run. The output is then this
```
Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne2x-photo-default-0.3.pkl.bz2` with trained model.

merc1.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'merc1.jpg'
```

This is using Docker version 1.12.0-rc3, build 91e29e8, experimental.

Clearly, the image is found at some point, but then can't be found. 

Am I entering the command wrong, or is this a bug of some sort?

**Comment by alexjc** [comment]
If you're not using the `alias`, you need to understand how `-v` works in Docker. Here it creates a folder as `/ne/input` so you need to specify that folder on command line too. I will update README with link to Docker's documentation about mounting folders.

**Comment by gducharme** [comment]
Got it, so /ne/input is also a local path. I took it to mean something like an SSH path aka from the root of the virtual machine. I changed the path, and now it's working. Thanks!
