### ISSUE TITLE
PIL.Image

### ISSUE THREAD

**Issue by xplkqlkcassia** [alexjc/neural-enhance#102]
Hey I'm a semi-noob trying to get neural-enhance up and running without Docker - for some reason Docker refuses to work on my machine. I'm running this command:

> python3 enhance.py --type=photo --model=repair --zoom=1 broken.jpg

but I keep getting this error

>   File "enhance.py", line 114, in <module>
>     import scipy.ndimage, scipy.misc, PIL.Image
> ImportError: No module named 'PIL'

I've pip installed Image, what thing/s am I doing wrong?

**Comment by alexjc** [comment]
You're missing `pillow`. Try `pip3 install -r requirements.txt` as in the README.

**Comment by xplkqlkcassia** [comment]
> Requirement already satisfied: pillow in /Library/Python/2.7/site-packages

**Comment by pojiratelnica** [comment]
use python3, create virtualenv with python3

**Comment by Jurph** [comment]
I've got a virtualenv stood up and have imported `pillow` per the README, but I am still getting the same error that the user above has. My python terminal in the venv can successfully import PIL, but when I run `python enhance.py` it says "No module named 'PIL'" ... and when I tell `pip` or `pip3` to install it, it says the requirement is satisfied and points to my venv.

I'm sure I'm missing something elementary but this is exasperating.
