### ISSUE TITLE
Example output from 4x photo default training file

### ISSUE THREAD

**Issue by geraldblank** [alexjc/neural-enhance#116]
@alexjc: I was able to get NE working in Windows 10 using Docker.

This is not really an issue, but more of an observation:

I decided to use NE to enlarge an outdoor image captured here in central Florida.

![floridapool-1x](https://cloud.githubusercontent.com/assets/24261759/21464867/ba7ad19e-c958-11e6-942a-096f4d0bfcbb.jpg)

I used the ne4x-photo-default-0.3.pkl.bz2 training file.

I have attached the original 1x test image (above)  and the enhanced 4x image (below).
Looking at the 4x output, I see that NE handled the foreground well, and there is excellent detail in the clouds.

![floridapool-4x](https://cloud.githubusercontent.com/assets/24261759/21464871/df4992c6-c958-11e6-9ae2-20c6a7773cbc.jpg)

On the downside, there are some stair-stepped pixels visible on the back of the chaise lounges in the middle of the swimming pool. The palm tree fronds also look somewhat rough. But considering how complex the original image is, I can't complain about the output.

Thanks for contributing this project!
Happy holidays.

**Comment by AxelStrem** [comment]
All the lines and borders look quite good, perhaps the foliage can be improved with more filters/training?  
Also it appears that saturation somewhat changed, interesting

**Comment by PaulConyngham** [comment]
Hey mate, what command line did you use to produce the 4x output? I attempting the following in the bash (with docker) with zero output results :(

enhance --zoom=4 Pictures/broken.jpg

**Comment by jacktive** [comment]
Honestly,i can not find out any difference in these pictures.I also wonder wether I us the script in the right way?

**Comment by munich-dev** [comment]
Increasing memory of docker daemon might help
