### ISSUE TITLE
Docker multiple images - No such file or directory

### ISSUE THREAD

**Issue by jakeelwes** [alexjc/neural-enhance#127]
Running docker GPU
Single images works fine so it can definitely find the directory

Thanks for any help :)

Command:
`enhance --model=repair pics/*.jpg`

```
Enhancing 465 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

pics/00050.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'pics/00050.jpg'
```

and if I run the enhance command from inside the pics folder with "*.jpg" I get the same problem

also get the same issue when putting multiple images in manually 
`enhance --model=repair 0.jpg 1.jpg`

with quotation marks around "pics/*.jpg"

just prints pics many times and says
`pics: file name too long.`

my .bashrc
```
alias enhance='function ne() { sudo nvidia-docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance:gpu ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'
```

**Comment by tshrjn** [comment]
Facing similar issue with just 1 image as well.
Command:
`enhance --zoom=1 --model=repair Images/PIC1.jpg`

But somehow it recognizes 2 images with this command as the error is as follows:

`
Enhancing 2 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

/Users/tshrjn/Projects/neural-enhance/Images/TJ.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tshrjn/Projects/neural-enhance/Images/TJ.jpg'
`



my .zshrc is as follows:

`
alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'
`

**Comment by jakeelwes** [comment]
Found the problem for me - it is expecting the image to be in a folder called 'input'

I'm using the command
`docker run --volume=$(pwd)/input:/ne/input -it alexjc/neural-enhance --zoom=4 --model=photo input/*.jpg
`

Its just a path problem - the way the docker is setup is to take images from the '/ne/input' path inside the docker. With multiple images this seems to be an issue (not sure why it's reading your one as two though)

So my little hack is to name my images folder 'input' cd one directory up and then use that folder as the workspace in the docker and as the input - $(pwd)/input:/ne/input & input/*.jpg

If that makes sense?

**Comment by tshrjn** [comment]
Oh cool, it fixed the issue for me as well. I simply put my images in a directory called input and did the same.

**Comment by joshuagordondba** [comment]
I am having the same issue but after I fixed that. I get the error permission denied. You can see it picks up the images as it has picked up the 1 image. Permissions set to 777. Any advice would be great.
docker run --volume=$(pwd)/input:/ne/input -it alexjc/neural-enhance --zoom=4 --model=default input/*.jpg
                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-photo-default-0.3.pkl.bz2` with trained model.

input/image.jpg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'input/image.jpg'
