### ISSUE TITLE
Resolution decreased

### ISSUE THREAD

**Issue by ggrrll** [alexjc/neural-enhance#130]
Hi ,

I don't know if/what are the theoretical limits of the tool,  but I just wanted to report my use case:

please, find attached the two version of the 

original 
<img width="1022" alt="original" src="https://cloud.githubusercontent.com/assets/15370425/23865745/f2f7315a-0816-11e7-8bef-6231909ee92a.png">

and 'neural-enhanced' version

<img width="1032" alt="after_neural-enhance" src="https://cloud.githubusercontent.com/assets/15370425/23865744/f2db92a6-0816-11e7-9d5f-6e3705602bbf.png">

**Comment by subzerofun** [comment]
What command line arguments have you used? 
The dimensions of the first image are 2044 x 1288 px and the 2nd is 2064 x 1280 px big.

So... if there are only 1X, 2X and 4X multiplications available something must have gone wrong with the upload.

If you want to do some tests i would suggest to try the algorithm with a photo – all the models were trained on photos, not graphics or text.

**Comment by ggrrll** [comment]
I used `python3.6 enhance.py --type=photo --model=repair --zoom=1 quanta_fig.png` 

Ah ok, so you don't think it will work for my original image ... (?) (plot)...
No, I am not interested for the moment in photos, I have improve that specific image...
Are you aware of techniques (deep L, etc...) that would work in my case?

Thanks

**Comment by subzerofun** [comment]
You could try waifu2x: https://github.com/nagadomi/waifu2x (network trained on comics)
Online-Tool: http://waifu2x.udp.jp/index.html

Software:
https://vectormagic.com/

But to be honest i don't think this will work in your case. The biggest problem is that your source image is already blurry (resized from low res -> bicubic interpolation?) and it's hard for these algorithms to extract detail from blurry spots. It works best when it can detect clear edges.

You would need a network trained only on grayscale plots, that would work! If you want to do it yourself you would need a few hundred (better thousand) images to train the network.

And i guess even then you would still get artifacts in the regions where there is text.

Do you maybe have the not-resized original image?

**Comment by ggrrll** [comment]
no, I don't  ...it's not my picture unfortunately

(I got some small improvements with _waifu2x_ ...thanks anyways! )
