### ISSUE TITLE
Repair model download link no longer works

### ISSUE THREAD

**Issue by tengr** [alexjc/neural-enhance#132]
ERROR: Model file with pre-trained convolution layers not found. Download it here...
https://github.com/alexjc/neural-enhance/releases/download/v0.3/ne2x-photo-repair-0.3.pkl.bz2

The above link doesn't work anymore.

**Comment by tengr** [comment]
all downloads should be here
https://github.com/alexjc/neural-enhance/releases/

**Comment by ikarosuusi** [comment]
Not only does not the above link not work, but the releases page doesn't offer a file with such name at all. Only a version that has "default" instead of repair.
