### ISSUE TITLE
What are the limits for source image?

### ISSUE THREAD

**Issue by BanzaiTokyo** [alexjc/neural-enhance#15]
I often get `Killed` even on relatively small images (like 600x600 pixels). I wonder what are the max dimensions of images that the script can enhance?

**Comment by alexjc** [comment]
Until I add tiled rendering, it depends on your system memory. 320x200 is the maximum I tried and the setting for the demo server too.

**Comment by BanzaiTokyo** [comment]
@alexjc how do you use tiled rendering?

**Comment by Carmezim** [comment]
this is weird, I used 317x299 198kb image and it didn't process.

**Comment by e-vlad** [comment]
Sorry, but if you don't want this limitation. You just can use Nnedi filter for avisynth/vaporosynth made by Tritical at 2007 (on Doom9). Neural trained filter that allow upscale images the same as neural-enchance in 2016 ;). GPU version also available.

**Comment by ProGamerGov** [comment]
@alexjc @BanzaiTokyo You could probably adapt [the method me and another individual came up with](https://github.com/jcjohnson/neural-style/wiki/Techniques-For-Increasing-Image-Quality-Without-Buying-a-Better-GPU), and then a third individual made into a simple script, for getting past GPU limitations: https://github.com/0000sir/larger-neural-style

We came up with the idea for Neural-Style, but I think it would work for Neural-Enhance as well. It divides the image into overlapping cropped pieces, and then once you have your U-pres output's, the pieces are put back together with a feathering technique.  For it to work with your project, the Neural-Style related aspects would have to be changed, but Neural-Enhance does seem to have a similar goal to the Tiled U-pres technique.

**Comment by wieczorek1990** [comment]
You have set a limit in code [here](https://github.com/alexjc/neural-enhance/blob/master/enhance.py#L520-L522).

**Comment by alexjc** [comment]
Try the new version 0.2, it should fix all this.

**Comment by BanzaiTokyo** [comment]
It looks like it is not completely fixed... 
```
Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne1x-small-0.2.pkl.bz2` with trained model.

./images/celeb1.png ....Traceback (most recent call last):
  File "enhance.py", line 585, in <module>
    out = enhancer.process(img)
  File "enhance.py", line 570, in process
    output[y*z:(y+s)*z,x*z:(x+s)*z,:] = np.transpose(repro[0] + 1.0, (1, 2, 0))[p*z:-p*z,p*z:-p*z,:]
ValueError: could not broadcast input array from shape (128,116,3) into shape (128,118,3)

```

**Comment by alexjc** [comment]
@BanzaiTokyo I found this bug too, will you submit a new Issue?

**Comment by BanzaiTokyo** [comment]
Looks like this particular issue (sorry for not submitting it in a separate thread) was fixed in the latest update. But now there is another problem, that I reported in [ https://github.com/alexjc/neural-enhance/issues/53](url)
