### ISSUE TITLE
always using CPU although GPU is there. 

### ISSUE THREAD

**Issue by elhoussinetalab** [alexjc/neural-enhance#166]
Hi, 

When I run any enhancement command, it says `Using the device 'cpu' for neural computation` which indicated that its not using GPU (GTx 1060), although I have installed CUDA, NVIDIA Drivers and CuDNN. 

The command I use to run the enhancer is something like : 
`python3 enhance.py --type=photo --model=default --zoom=2 ninput2.jpg`

I am on Ubuntu 16

Thanks.

**Comment by AlKul** [comment]
... --device=gpu0
?

But I didn't manage to start it on gpu neither on windows nor ubuntu 16.04

**Comment by bonejay** [comment]
Same issue. I have changed .theanorc to the cuda path and cuda is working but is still is not recognizing the gpu. I am on 17.04

**Comment by AlKul** [comment]
I was talking about "manual installation", but on ubuntu nvidia-docker didn't work neither, though i followed all the instructions :(

**Comment by elhoussinetalab** [comment]
@AlKul @bonejay **solved** by using --device=cuda0 (make sure you isntalled theano, cudnn properly. one way to test is to use `sudo python3 -c "import theano"` which should run with no errors.)

**Comment by bonejay** [comment]
Cuda works. Nvidia docker not really. Same with theano. @elhousesinetalab

Keep in mind that using cuda does not mean anything since it can fall back to CPU. To be sure you should use the gpu argument

**Comment by bonejay** [comment]
Problem with Theano:
 sudo python3 -c "import theano"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'theano'
bone@bone-System-Product-Name:~$ conda install theano pygpu
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/bone/miniconda3:
#
pygpu                     0.6.9                    py36_0  
theano                    0.9.0                    py36_0
