### ISSUE TITLE
output is almost same as input 

### ISSUE THREAD

**Issue by elhoussinetalab** [alexjc/neural-enhance#167]
Here's my input image https://ibb.co/mdiyBv and here is the ground https://ibb.co/gDzAPF. 

This is the command I use 

`python3 enhance.py --type=photo --zoom=2 ninput2.jpg`

**Comment by bonejay** [comment]
You have to downscale the image (resize) not pixelate it

**Comment by elhoussinetalab** [comment]
@bonejay isn't that the same thing?

**Comment by elhoussinetalab** [comment]
okay, it worked.

**Comment by elhoussinetalab** [comment]
okay, it worked
