### ISSUE TITLE
Docker Problems: "No such file or directory"

### ISSUE THREAD

**Issue by Thibaudz** [alexjc/neural-enhance#17]
Hi

I use docker image on Mac OS.
When I launch enhance my_file.jpg 
I get this issue:

```
Traceback (most recent call last):
  File "enhance.py", line 510, in <module>
    out = enhancer.process(scipy.ndimage.imread(filename, mode='RGB'))
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'my_file.jpg'
```

What I do wrong?

**Comment by alexjc** [comment]
The `images` folder is mounted into the docker instance. Does this folder exist locally in your current directory?

**Comment by kommen** [comment]
@alexjc I have the same issue when I use the docker image with the alias as suggested in the README.  It works for me when using a different mount point inside the container, e.g `/ne/images1` instead of `/ne/images`.

**Comment by alexjc** [comment]
Very strange, but thanks for the reports. If any Docker experts know why this is happening let me know!

**Comment by Aidenjl193** [comment]
Been having the same issues with whatever mount point I use, could just be that I have no clue how to use docker. Also I'm on windows so i think the filesystem stuff is a bit different

**Comment by alexjc** [comment]
@Aidenjl193 On Windows, try using folders that are contained within your `C:\Users\<profile>\` folder. Docker is very weird about this, some kind of security for mounting things.

**Comment by ddmng** [comment]
@Aidenjl193 if you run:
`docker run --entrypoint bash  -v $PWD/images:/ne/images -it alexjc/neural-enhance`

can you see the `./images` folder inside the container and files inside it?

**Comment by Aidenjl193** [comment]
@ddmng if I run that I get the error 
docker: Error response from daemon: create $PWD/images: "$PWD/images" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
See 'docker run --help'.

God I have no clue what I'm doing with docker but I've been itching to play around with this all day

**Comment by ddmng** [comment]
@Aidenjl193 sorry, I've just seen you're under windows. Then you should issue the same command changing $PWD with your current path.

**Comment by xuyifeng-nwpu** [comment]
I solved this problem.You should run this code :enhance ne/images/***.jpg.

**Comment by rlqualls** [comment]
Renaming `images` to  `images1` on both sides worked for me.

**Comment by ddmng** [comment]
On Linux, using `${PWD}` instead of `$(pwd)` for me works.

Can't test on Windows, but maybe a `%CD%` does the job.

**Comment by xuyifeng-nwpu** [comment]
i solved this problem.
you   run   this code:   enhance  /ne/images/****.jpg.

 /ne/images/*    must   be your  docker's container

**Comment by purpleidea** [comment]
Here's the general fix: https://github.com/alexjc/neural-enhance/pull/36
All the other fixes are herrings.

**Comment by hemel-cse** [comment]
It works see here [Issue 28](https://github.com/alexjc/neural-enhance/issues/28)

**Comment by alexjc** [comment]
Try the latest `alias` from the README too, open an issue if there are any other problems.
