### ISSUE TITLE
enhance.py: error: unrecognized arguments: --scales=2

### ISSUE THREAD

**Issue by shede1988** [alexjc/neural-enhance#183]
enhance.py: error: unrecognized arguments: --scales=2
When I enter the following command:
     python3.5 enhance.py --train "data/*.jpg" --model custom --scales=2 --epochs=50

**Comment by cyberthrone3** [comment]
@shede1988 There are a list of possible arguments in enhance.py
--train-scales is the most similar to --scales there. Try use this one.
Probably, a name of the argument was changed in a development process.

But maybe I'm wrong and --scales and --train-scales are two different things

**Comment by shede1988** [comment]
Thank you !@cyberthrone3
