### ISSUE TITLE
Always getting a FileNotFoundError

### ISSUE THREAD

**Issue by mstapfner** [alexjc/neural-enhance#193]
Hello everybody, I`m trying to run the algorithm on Docker (Mac OS X), but every time I get the following error:

`docker run -v /Users/STAPFM/Documents/Privat/Various/Image-Enhance/ne/input:/ne/input -it alexjc/neural-enhance *.jpeg
...

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 3 image(s) specified on the command-line.
  - Loaded file `ne2x-photo-default-0.3.pkl.bz2` with trained model.

one.jpeg Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'one.jpeg' `

**Comment by jhurliman** [comment]
I found a workaround for now, but not sure why this isn't working as documented.

`docker run -v /Users/STAPFM/Documents/Privat/Various/Image-Enhance/ne/input/one.jpeg:/ne/input/one.jpeg -it alexjc/neural-enhance /ne/input/one.jpeg`

**Comment by whyboris** [comment]
I spent a bunch of time until I read more of the _Issues_ here figured out that in my case it was a problem with `zsh`. If you're using `zsh` try this solution: 
https://github.com/alexjc/neural-enhance/issues/176#issuecomment-368919333

**Comment by mstapfner** [comment]
Thank you very much!
