### ISSUE TITLE
�[1;31mERROR: Model file with pre-trained convolution layers not found. Download it here...�[0;31m https://github.com/alexjc/neural-enhance/releases/download/v0.1/ne4x-medium-0.1.pkl.bz2�[0m

### ISSUE THREAD

**Issue by ruah1984** [alexjc/neural-enhance#196]
the web no more active. can you all please share it again??

**Comment by Hunterwolf88** [comment]
same here

**Comment by Hisairnessag3** [comment]
Just put them in the root directory and not train, then you are good to go.

**Comment by moun3imy** [comment]
Just copy that link into your browser, download that file and then move it to your neural-enhance-master folder, then reexecute the command, it will work

**Comment by ruah1984** [comment]
Ok ,
