### ISSUE TITLE
Can't load model (ValueError: too many values to unpack (expected 2))

### ISSUE THREAD

**Issue by BanzaiTokyo** [alexjc/neural-enhance#2]
I am trying to have a test run with `python enhance.py image.png`
where python is Python 3.5.2 |Anaconda custom (64-bit) and I get the  following error:

```
Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-medium-0.1.pkl.bz2` with trained model.
Traceback (most recent call last):
  File "enhance.py", line 500, in <module>
    enhancer = NeuralEnhancer()
  File "enhance.py", line 423, in __init__
    self.model = Model()
  File "enhance.py", line 218, in __init__
    config, params = self.load_model()
ValueError: too many values to unpack (expected 2)

```

**Comment by alexjc** [comment]
Thanks for reporting. Can you also try again with `--model=small`? Did you download the file from the releases?

**Comment by BanzaiTokyo** [comment]
`--model=small 
`gives pretty much the same result:
```
python enhance.py banzaitokyo.png --model=small
                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-small-0.1.pkl.bz2` with trained model.
Traceback (most recent call last):
  File "enhance.py", line 500, in <module>
    enhancer = NeuralEnhancer()
  File "enhance.py", line 423, in __init__
    self.model = Model()
  File "enhance.py", line 218, in __init__
    config, params = self.load_model()
ValueError: too many values to unpack (expected 2)
```
The file? If you are talking about the model, it is the thing I am not sure I am doing right:
when I first launched enhance.py without parameters it said that the model can bedownloaded from https://github.com/alexjc/neural-enhance/releases/download/v0.1/ne4x-medium-0.1.pkl.bz2
However wget saved it as vgg19_conv.pkl.bz2 (I have no idea why) So to get the message above I renamed vgg19_conv.pkl.bz2 to ne4x-medium-0.1.pkl.bz2

Now I tried downloading the model again and somehow it was downloaded with the correct name and the script ran fine. So I am not sure where the error came from.

**Comment by alexjc** [comment]
OK, I will try to make the error message a bit more clear. You don't need vgg19 if you're just applying super-resolution.
