### ISSUE TITLE
Docker execution does not recognize file in current directory

### ISSUE THREAD

**Issue by mvrozanti** [alexjc/neural-enhance#216]
Hello there

I followed the instructions in the README (added 
```
alias enhance='function ne() { docker run --rm -v "$(pwd)/`dirname ${@:$#}`":/ne/input -it alexjc/neural-enhance ${@:1:$#-1} "input/`basename ${@:$#}`"; }; ne'
```

 to `.bash_aliases`) for running with docker and got the following error:

```
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 2 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

$(KGrHqV,!p8E63ZwikhvBO2snCohIg--60_3.JPG Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '$(KGrHqV,!p8E63ZwikhvBO2snCohIg--60_3.JPG'
```

`$ uname -mrs`
`Linux 5.0.2-arch1-1-ARCH x86_64`

**Comment by ImAWizardLizard** [comment]
I'm having the same issue, I reckon it might be a problem with the alias provided, will update you on if I make it work.

**Comment by quintendewilde** [comment]
I'm having the same issue `input/broken.png Traceback (most recent call last):
  File "enhance.py", line 583, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'input/broken.png'`


Where should I find this folder or create this folder under the alias?

**Comment by mvrozanti** [comment]
@quintendewilde I belive that's another issue

**Comment by FrancescoSaverioZuppichini** [comment]
same error

**Comment by FlamesoFF** [comment]
same

**Comment by Gyvastis** [comment]
Using bash instead of zsh did the trick.

**Comment by AnuCre** [comment]
same error..what do

**Comment by FrancescoSaverioZuppichini** [comment]
use bash instead of zsh
