### ISSUE TITLE
Training takes significantly longer each epoch

### ISSUE THREAD

**Issue by msfeldstein** [alexjc/neural-enhance#23]
When training on the GPU, each epoch takes much longer than the previous, which makes me think that there's some type of leak going on.  With my understanding of how this works, it seems like each epoch should be a constant time since it's doing the same number of fwd/back props, and should be using the same amount of memory, though I am a beginner so if I am wrong here please let me know.

Command i'm using to train on a GTX1070 on ubuntu:
```python3 enhance.py --train "milkyway-dataset/*.jpg" --model custom --scales=2 --epochs=50 --perceptual-layer=conv2_2 --smoothness-weight=1e7 --adversary-weight=0.0 --generator-blocks=4 --generator-filters=64 --device=gpu0```

Timings are 
```
Epoch #1 at 81.6s, lr=1.00e-05                                                                            
  - generator total=1.30e+05 prcpt=1.29e+05 smthn=6.57e+02 advrs=0.00e+00
  - discriminator 0.732835 15 -0.732835 15
Epoch #2 at 163.1s, lr=1.00e-04                                                                            
  - generator total=1.09e+05 prcpt=1.08e+05 smthn=1.19e+03 advrs=0.00e+00
  - discriminator 0.923685 15 -0.923685 15
  - generator now optimizing against discriminator.
Epoch #3 at 244.6s, lr=1.00e-04                                                                            
  - generator total=8.22e+04 prcpt=7.95e+04 smthn=2.69e+03 advrs=0.00e+00
  - discriminator 0.960172 15 -0.960172 15
Epoch #4 at 326.2s, lr=1.00e-04                                                                            
  - generator total=7.53e+04 prcpt=7.19e+04 smthn=3.40e+03 advrs=0.00e+00
  - discriminator 0.967729 15 -0.967729 15
Epoch #5 at 407.8s, lr=1.00e-04                                                                            
  - generator total=7.45e+04 prcpt=7.11e+04 smthn=3.46e+03 advrs=0.00e+00
  - discriminator 0.977347 15 -0.977347 15
Epoch #6 at 489.2s, lr=1.00e-04                                                                            
  - generator total=6.72e+04 prcpt=6.40e+04 smthn=3.23e+03 advrs=0.00e+00
  - discriminator 0.981071 15 -0.981071 15
```

all the way up to a few thousand.  Is this a problem or am i misunderstanding it?

**Comment by alexjc** [comment]
Ah `at` means it's the cumulative time not the time for that epoch. The time would otherwise be almost identical each line ;-)

**Comment by msfeldstein** [comment]
Of course.  Anyway, thanks for the great well organized project :)
