### ISSUE TITLE
Failing at address: 0x7fb8718fa20d

### ISSUE THREAD

**Issue by minenkod** [alexjc/neural-enhance#234]
i"m using Google Colab to run this and keep getting this error message:

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne1x-photo-repair-0.3.pkl.bz2` with trained model.

broken.jpg .................................................................................

[f83b50c07522:01951] *** Process received signal ***
[f83b50c07522:01951] Signal: Segmentation fault (11)
[f83b50c07522:01951] Signal code: Address not mapped (1)
[f83b50c07522:01951] Failing at address: 0x7fb8718fa20d
[f83b50c07522:01951] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fb8743a1890]
[f83b50c07522:01951] [ 1] /lib/x86_64-linux-gnu/libc.so.6(getenv+0xa5)[0x7fb873fe0785]
[f83b50c07522:01951] [ 2] /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4(_ZN13TCMallocGuardD1Ev+0x34)[0x7fb87484be44]
[f83b50c07522:01951] [ 3] /lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0xf5)[0x7fb873fe1615]
[f83b50c07522:01951] [ 4] /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4(+0x13cb3)[0x7fb874849cb3]
[f83b50c07522:01951] *** End of error message ***

**Comment by rdevi-pz** [comment]
@minenkod You identified a means to fix the issue? I am facing the same problem.

**Comment by minenkod** [comment]
Not using Google colab and switching to docked running locally was my fix :)
