### ISSUE TITLE
How to run the docker image as container.

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [alexjc/neural-enhance#24]
Now  the docker image had been builded.  The code is error " docker run -v $(pwd)/images:/ne/images -it alexjc/neural-enhance". I want to run the container directly.

If the grammar of the sentence is wrong ,could you correct.

**Comment by ddmng** [comment]
I have this problem too. For some reason the expansion of `$(pwd)` is not done, so docker is mounting `/images` instead. Using `${PWD}` works for me (Linux/cpu version).

**Comment by xuyifeng-nwpu** [comment]
@ddmng  thank your reply. I used your method :"docker run -v ${pwd}/images:/ne/images -it alexjc/neural-enhance".     However some error message appeared.
ERROR: Specify the image(s) to enhance on the command-line.

I want to run the enhance.py in docker container .So that i can view and modify the code.

**Comment by ddmng** [comment]
@xuyifeng-nwpu you only have to add to the command the name of the image(s) to enhance, for example:

`docker run -v ${pwd}/images:/ne/images -it alexjc/neural-enhance images/test.jpg`

**Comment by ddmng** [comment]
@xuyifeng-nwpu if you modify the python source, you have to build again the docker image with a:
```
	docker build -t alexjc/neural-enhance -f docker-cpu.df .
```
I use a `Makefile` for this in my forked repo: https://github.com/ddmng/neural-enhance

**Comment by alexjc** [comment]
Try the latest `alias` from the README and let me know if there are any other problems.
