### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ruevers** [alexjc/neural-enhance#246]
After download file, the error continue

ERROR: Model file with pre-trained convolution layers not found. Download it here...
https://github.com/alexjc/neural-enhance/releases/download/v0.3/ne1x-photo-repair-0.3.pkl.bz2

comand:
!python3 enhance.py --type=photo --model=repair --zoom=1 /content/extracted_1.png

**Comment by detkov** [comment]
You don't have to decompress them, leave as it is with ".bz2" extension
