### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by jcklpe** [alexjc/neural-enhance#247]
Trying to get neural-enhance working in a notebook environment [using Google Colab here.](https://colab.research.google.com/drive/1EUkddyRwAqWmyGsm-d1VkmLg6cuKfwUm?usp=sharing) 

I've loaded the  pretrained models in the working directory and it seems that they are getting loaded but having some kind of issue.

**Comment by AlexanderKozhevin** [comment]
@jcklpe Can you make it public, please?

**Comment by jcklpe** [comment]
@AlexanderKozhevin  I ended up getting things working with pyanime4k though it took some weird work arounds. The public Colab for my final product can be found here: https://colab.research.google.com/drive/1MAXjPCb8Aomn2dQyi5R-LOgtLSkG-i-a?usp=sharing

**Comment by jcklpe** [comment]
@AlexanderKozhevin I've also made a github repo with a friend for these. trying to build up general purpose neural network scripts that can easily be run in a Colab notebook environment. You're more than welcome to come collaborate with me on producing more: https://github.com/jcklpe/neural-network-art
