### ISSUE TITLE
Do the docker need VGG19?

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [alexjc/neural-enhance#25]
You say that "You'll also need to download this pre-trained neural network (VGG19, 80Mb) and put it in the same folder as the script to run."
If using docker enhance the image ,is the VGG19 need?

Why my Implementation Effect isn't so perfect ?

**Comment by alexjc** [comment]
It takes many hours to train the models. You only need VGG19 if you plan to train the model.

Does that answer your questions?

**Comment by JamesLuoau** [comment]
can we add VGG19 into docker? As I think people may need train the model in side it.

**Comment by xuyifeng-nwpu** [comment]
@alexjc thank you. Your previous work :neural doodle  had also been concerned by our group. It's magnificent.   But about  neural_enhance  using the docker method ,my enhance effect was little almost nothing change between source and target picture. 

My method  followed yours:
alias enhance="docker run -v $(pwd)/images:/ne/images -it alexjc/neural-enhance"
enhance ne/images/example.jpg

I tried add "--mode=large", however no effect.

**Comment by wieczorek1990** [comment]
I think most people will not use it. Why make the docker image even bigger. The code for training already mentions where you can download the file in an [error message](https://github.com/alexjc/neural-enhance/blob/master/enhance.py#L325-L328).

**Comment by alexjc** [comment]
OK, I agree it's not needed. You can download the VGG file inside the docker using `--entrypoint /bin/bash` as argument, then running `wget` manually. Closing this...

**Comment by eugenio412** [comment]
I'm not familiar with docker and it took a while to make me run the script. However I cannot understand how to add the pre trained neural network VVG19 to the image, could someone explain it to me?

**Comment by wieczorek1990** [comment]
If using the same data volume as in README, put the file in the shared directory, then run the docker container with bash as entrypoint and move the file from `/ne/input/` to `/ne/`. Then you will be able to train your own network which will have the filename in this format `ne${scales}x-${model}-${version}.pkl.bz2`.
Your network will have model equal to custom, the current version is `0.2` and scales is set using command line argument. You will need to pass an argument (`--model custom`) when running the script.
