### ISSUE TITLE
No Windows support yet, eh?

### ISSUE THREAD

**Issue by HWiese1980** [alexjc/neural-enhance#27]
Well, I guess Windows isn't the OS of choice for machine learning tasks. Still, it would be great.

**Comment by ssccsscc** [comment]
It works for me. I followed instruction in the readme.

**Comment by HWiese1980** [comment]
Huh, didn't see that for some reason... testing it! Thanks!

**Comment by XPanniX** [comment]
@HWiese1980 When I'm running the script from the Windows Python Console it says that it can't find the pre-trained convolution layers, even though I downloaded them and placed them in the same directory as the enhance.py script. Did that happen to you as well, if so how did you fix it?

**Comment by HWiese1980** [comment]
Nope, didn't experience this issue. Though I've stopped trying to get it running because it turned out to become a huge amount of yak shaving in the end. Even without CUDA. Python based machine learning under Windows is still a pain in the ass. Thus, recommendation: use Linux.
