### ISSUE TITLE
File Not Found (Docker Issues)

### ISSUE THREAD

**Issue by hemel-cse** [alexjc/neural-enhance#28]
![screenshot from 2016-10-31 15-32-14](https://cloud.githubusercontent.com/assets/6664461/19849810/52ddf76c-9f7f-11e6-9493-5ebf1bad7797.png)

**Comment by JosephRedfern** [comment]
Same issue here.

**Comment by daveredfern** [comment]
I also get this.

Also @JosephRedfern, Hi! Matching surname.

**Comment by conroyp** [comment]
I ran in to the same issue on OS X - changing the alias from using `${pwd}` to `${PWD}` sorted it out for me.

**Comment by ronakg** [comment]
I've tried all the suggestions above, but nothing works. Get ``FileNotFoundError`` every time. The file ``test.jpg`` is in the local folder where the script is being run from.

```
rogandhi at ROGANDHI-M-61CN in ~ 15:01:46
1> docker run -v $(PWD)/images:/ne/images -it alexjc/neural-enhance test.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-small-0.1.pkl.bz2` with trained model.

test.jpg
Traceback (most recent call last):
  File "enhance.py", line 519, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'test.jpg'
```

**Comment by alexjc** [comment]
Try debugging it with this:
`docker run -v $(PWD)/images:/ne/images --entrypoint /bin/bash -it alexjc/neural-enhance`
Then type `ls /ne/images` and see if it contains what you expect.

On windows, you may need to mount within C:\Users\<username> folder for it to work (permissions).  Some users also reported results using `image1` as a folder name.

**Comment by alexjc** [comment]
@ronakg Move your JPG into the `images` folder within the current working folder, otherwise docker won't find it.

@conroyp What version of MacOS are you running? I wonder if $(PWD) uppercase works on Linux too...

**Comment by ronakg** [comment]
@alexjc Thanks. Moving the image to ``images`` folder worked.

**Comment by purpleidea** [comment]
Here's the general fix: https://github.com/alexjc/neural-enhance/pull/36
All the other fixes are herrings.

**Comment by hemel-cse** [comment]
Ok thank you
solved by this commit
![screenshot from 2016-11-01 15-36-03](https://cloud.githubusercontent.com/assets/6664461/19885519/34b83b92-a049-11e6-8935-15bd0b07653f.png)
