### ISSUE TITLE
The effect of docker is none.

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [alexjc/neural-enhance#32]
run the following operation or code:
1:docker pull alexjc/neural-enhance    #build the docker image from dockerhub
2:alias enhance="docker run -v $(pwd)/images:/ne/images -it alexjc/neural-enhance"     #i try respectively (pwd) and {pwd}
3:copy the picture into the shared folder images          #limit the picture pixels
4: enhance /ne/images/sample.jpg
5:About a minute later  the enhanced picture created.   However the source picture and the enhanced one is same definition.

**Comment by alexjc** [comment]
Try the new alias I just added to the README? This one is not as intuitive to use for those not familiar with docker's `-v`.

**Comment by hpiedcoq** [comment]
Nope Alexjc, doesn't work better for me. On Lubuntu 16.10.
Same issue as everybody.
'
docker: Error parsing reference: "$1`:/ne/input" is not a valid repository/tag.
See 'docker run --help'.
'


I went back to " alias enhance='docker run -v ${PWD}:/ne/images -it alexjc/neural-enhance' "
and get the same error.
`2.jpg
Traceback (most recent call last):
  File "enhance.py", line 519, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '2.jpg'
`

**Comment by alexjc** [comment]
Fixed by [0c31e53]. See the README for new `alias`, try again and let me know!
