### ISSUE TITLE
Why my effect was not obvious?

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [alexjc/neural-enhance#41]
I used the docker method to  enhance the image, however the effect was un****
This is source picture:
![face_v5](https://cloud.githubusercontent.com/assets/21265053/19954062/86e51e82-a1af-11e6-84f1-5469aa7cbad8.jpg)

While the picture blow shows is enhanced picture:
![face_v5_ne4x](https://cloud.githubusercontent.com/assets/21265053/19954068/9377751e-a1af-11e6-9c56-fd73f8025d01.png)
I think only the latter's size is more bigger and their defination is same.

Do i need pretrain the face database so to get bright result?
Can achieve so good effect only using author's model:`ne4x-medium-0.1.pkl.bz2`?

**Comment by alexjc** [comment]
There are two problems here:
- You're using an input image that has 4x4 sized pixels (used for demo only).
- The network trained on faces is not yet available publicly.

Find a real face picture and down-sample that, try again ;-)

**Comment by wieczorek1990** [comment]
![apptension_merged](https://cloud.githubusercontent.com/assets/1643947/19964512/67bbac98-a1c2-11e6-852b-69aa499a08df.jpg)

Left original, right was down-sampled first then used as input.

**Comment by xuyifeng-nwpu** [comment]
@alexjc Can you tell me what is 4x4 sized pixels ? My source picture's width and height pixels all are more than 100 pixels.
Now i used the images provided by @wieczorek1990 through the docker method however the effect is bad.
------------------------------------------------
source picture is below:
![face_v9](https://cloud.githubusercontent.com/assets/21265053/19968213/9b4aba3a-a20e-11e6-8a14-f631358b92f1.jpg)
enhenced picture  is below: 
![face_v9_ne4x](https://cloud.githubusercontent.com/assets/21265053/19968215/9d4efc4c-a20e-11e6-8783-726d2f274a0a.png)

#My shell  code is below.  The absolute path used in code.  These code can work.
docker run -v /home/xyf/images:/root/ne/images --entrypoint /bin/bash -it alexjc/neural-enhance
/opt/conda/bin/python3.5 enhance.py /root/ne/images/face_v5.jpg

**Comment by alexjc** [comment]
Try again with version 0.2, just released. It has the ability to fix images 1:1 without increasing resolution.
