### ISSUE TITLE
Is it possible to create executable alias on Windows cmd?

### ISSUE THREAD

**Issue by Sunsvision** [alexjc/neural-enhance#43]
I am trying to execute enhance on Windows 10 64 bit but don't know how to create executable alias? i was trying to do this using Mingw64 but when trying to execute 'enhance test.gif' command i get:
> the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

So i think better is to use default Windows cmd, but did not know how to set 'enhance' command for it.

**Comment by wieczorek1990** [comment]
You better ignore the alias setting and just use the docker command that is defined in the aliased function.

You should have docker installed and available in command line.

```
docker run -v images:/ne/input -it alexjc/neural-enhance input/image.png
```

It downloads and runs a docker image named `alexjc/neural-enhance`, creates a data volume linking `images` directory on host to `/ne/input` in container and passes the `input/image.png` as the entrypoint argument (it has to start with `input/` because we mounted the data volume there and the script working directory is `/ne/`). The -it is for enabling interactive tty.

**Comment by Sunsvision** [comment]
Thx for quick solution! I see execution log now, but seems like have some path problems. I've created images in test folder, ran cmd under test folder, copied file 3.gif to images folder and executed next command:
> docker run -v images:/ne/input -it alexjc/neural-enhance input/3.gif

As i understood from your message - 'images' is a name of folder on Windows host for mounting as '/ne/input' on Docker. So this should work. But i get:
> FileNotFoundError: [Errno 2] No such file or directory: 'input/3.gif'

Tried 'C:\test\images' but also no success.. could you help with this please?

And 2d question - is it possible to specify trained model? As i see by the default `ne4x-small-0.1.pkl.bz2` are used but i also want to test it with vgg19_conv.pkl.bz2 downloaded from the link in desctiption.

**Comment by alexjc** [comment]
Docker is not great on windows. You may need to put things inside C:\Users\<username>. Also you need to understand `-v` and how Docker uses them before considering this option... The alias now takes care of this for you because it's not trivial. Maybe a `.bat` file?

**Comment by Sunsvision** [comment]
thanks for the help! found next solution:
> docker run -v "c:/images/":/ne/input -it alexjc/neural-enhance input/test.jpg

as for using vgg19_conv.pkl.bz2 model question is still actual - is it possible to use it when running docker image?

**Comment by wieczorek1990** [comment]
You would need to copy the file into the container or put it in the data volume and move it to the right place in the container. You can use the containers Bash shell using `docker run` with `--entrypoint bash` argument.

**Comment by alexjc** [comment]
@Sunsvision As for your last question, the file `vgg19_conv.pkl.bz2` is only for training and if you train in Docker it will be rather slow!

**Comment by Sunsvision** [comment]
thx guys!
