### ISSUE TITLE
UX issue/unsupported relative path/no such file or directory

### ISSUE THREAD

**Issue by Rasie1** [alexjc/neural-enhance#45]
- pulled docker image
- added alias `alias enhance='function ne() { sudo docker run -v $(PWD)/`dirname $1`:/ne/input -it alexjc/neural-enhance input/`basename $1`; }; ne'`
- `enhance IMG_20161029_194946.jpg`
Output:

```
PWD: command not found
                             _              _                           
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___  
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \ 
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/ 
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___| 

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-small-0.1.pkl.bz2` with trained model.

input/IMG_20161029_194946.jpg
Traceback (most recent call last):
  File "enhance.py", line 519, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'input/IMG_20161029_194946.jpg'
```

- a lot of tries before I realized that I shouldn't put relative paths here. Global path worked

Thanks.

system: Ubuntu 16.04

**Comment by wieczorek1990** [comment]
The instructions are wrong. Replace `PWD` with lowercased version `pwd`. It was supposed to call the pwd command.

**Comment by Rasie1** [comment]
It's copied from README.md; I only added sudo

**Comment by wieczorek1990** [comment]
I am not the author. ;-)

Maybe @alexjc meant $PWD variable. $(pwd) works too.

**Comment by xuyifeng-nwpu** [comment]
@ Rasie1  Maybe you  can use the absolute path.

**Comment by alexjc** [comment]
Hmm, some MacOS users reported problems with lowercase `pwd` but it seems to be supported on my machine. I'll change it to lowercase if it's the only option on Linux.

**Comment by Rasie1** [comment]
Yes, `pwd` is an executable, and `PWD` is an environment variable, you can write `$PWD` or `$(pwd)`. 
I guess the issue may be closed
