### ISSUE TITLE
Running alias instructions in readme

### ISSUE THREAD

**Issue by wieczorek1990** [alexjc/neural-enhance#46]
I would prefer if the instructions for running neural-enhance using docker did not involve settings an alias.

They could be replaced with something like this in Bash:

```
$ cd images
$ ls images
image.png
$ sudo docker run -v `pwd`:/ne/input -it alexjc/neural-enhance input/image.png
```

**Comment by alexjc** [comment]
That works too! What's the problem with an alias?

**Comment by wieczorek1990** [comment]
I think aliases are very personal and that most people would like to get shortest possible shell instructions instead.

**Comment by alexjc** [comment]
I'm wondering about adding it alongside...

There were three issues (and more comments in other issues) opened because people didn't understand exactly how Docker's `-v` folder mapping works, couldn't figure out the directories.  The new `alias` deals with that transparently.

**Comment by wieczorek1990** [comment]
But `alias` command is dependent on the shell and people already started running `neural-enhance` on Windows. Then you have people who want to use more features and need to ssh into the container and they most likely will have to extract the right command from the alias.

You are right that it is better to have both instructions.

**Comment by savdop** [comment]
Regarding using alias, I cannot get it to work on ubuntu. Keep getting error 
bash: syntax error near unexpected token `(' 
This seemed like the right place to ask. 

Thanks!

**Comment by alexjc** [comment]
@savdop What version of ubuntu and bash? Do you have any more details with the error?

**Comment by alexjc** [comment]
@wieczorek1990 The alias now passes through all options you specify before the filename, so you don't need to ssh into Docker—luckily. Anyone doing advanced operations will likely want to install without the container for extra speed (it's much slower inside Docker).

**Comment by wieczorek1990** [comment]
If I installed all things I want to test on my host I would have a cluttered system.
People do deployments with Docker these days.

**Comment by alexjc** [comment]
You can run locally in a Python virtualenv without cluttering your system, as described in the setup instructions.  Not everyone uses Docker and certainly not for everything! [[1](https://thehftguy.wordpress.com/2016/11/01/docker-in-production-an-history-of-failure/)]
