### ISSUE TITLE
ValueError on enhance

### ISSUE THREAD

**Issue by sbartram** [alexjc/neural-enhance#48]
I tried a couple of images using the docker image:

$ enhance images/me.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne1x-small-0.2.pkl.bz2` with trained model.

input/me.jpg .Traceback (most recent call last):
  File "enhance.py", line 585, in <module>
    out = enhancer.process(img)
  File "enhance.py", line 570, in process
    output[y*z:(y+s)*z,x*z:(x+s)*z,:] = np.transpose(repro[0] + 1.0, (1, 2, 0))[p*z:-p*z,p*z:-p*z,:]
ValueError: could not broadcast input array from shape (128,0,3) into shape (128,2,3)

**Comment by alexjc** [comment]
This is fixed with [de047d6] so I'm closing this.
