### ISSUE TITLE
Poor quality output image 

### ISSUE THREAD

**Issue by davidemorotti** [alexjc/neural-enhance#49]
Hi,

I'm giving a try to your tool but with the suggested command I actually get an image that is worse than the original one. Here the result of my test:
[http://imgur.com/a/BJLNY](http://imgur.com/a/BJLNY) (the first image is the original one, the second one is the result I get)

Here the command I used:
`enhance --zoom=1 --model=small images/example.jpg`

Do I need to change some configurations?

I'm on a Mac mini with macOS Sierra (installed the tool via Docker)

**Comment by kgrm** [comment]
You're not supposed to upscale the image before feeding it to the neural network, examples in the readme are just shown like that for demonstration.

**Comment by eyeonx** [comment]
Thanks @kgrm, but I even tried without parameters and is still not working. What command do you use normally?

**Comment by kgrm** [comment]
First off, as mentioned, you shouldn't oversample the images before using them as input. Therefore, this is the image I used:

![example_small](https://cloud.githubusercontent.com/assets/18569293/20015687/c1cb27b0-a292-11e6-84c3-3ceb73a366e2.png)

And the command I used is `python3 enhance.py example_small.png --model=large`, and this is the result:

![example_small_ne4x](https://cloud.githubusercontent.com/assets/18569293/20015732/f54369b8-a292-11e6-897f-3dfcf711eb7e.png)

**Comment by attibalazs** [comment]
How did you solve this ? i got the same issue but was running it on windows 7.

**Comment by davidemorotti** [comment]
Hi @attibalazs, I didn't solve the problem. As someone suggested you just need to run the command:
`enhance --model=large images/example.jpg`

However the trained model isn't existing yet for the current version of `neural-enhance`.

I closed the issue because I no python knowledge and I don't know how to download and use trained models. Too complicated for me.

I hope someone else could help you solve your problem.

**Comment by attibalazs** [comment]
hi @davidemorotti i did download v1 and used the trained models they provided but still got the same issue. Anyway looks like they are working on it, i`ll check back later and try again.

**Comment by davidemorotti** [comment]
@attibalazs how did you integrate the trained model into the Docker image?

**Comment by attibalazs** [comment]
i didnt use docker (couldn`t use it because of issues with proxy), i set-up a conda environment and did ran it from there.
