### ISSUE TITLE
Please include some sample input and processed image

### ISSUE THREAD

**Issue by vi** [alexjc/neural-enhance#50]
So that one can test `enhance.py` with pre-defined input image and `ne1x-small-0.2.pkl.bz2` and compare the result to pre-defined output image.

It can be like `docs/sample_input.png` and `docs/sample_output_1x.png`.

It is needed to ensure the system is actually working right.

For example, I try to to do this `./enhance.py --zoom 1 h.png` on this image:

![h](https://cloud.githubusercontent.com/assets/173219/20014959/5375e5b0-a2ca-11e6-88a6-ff1e9450b211.png)

and get this:

![h_ne1x](https://cloud.githubusercontent.com/assets/173219/20014969/5c926d58-a2ca-11e6-8c2b-476fdd549a50.png)

(similar for `--zoom 2x`). I doubt it is expected behaviour. With pre-defined input and output images it can work like a simple acceptance test, showing if the system is correctly configured to run neural-enhance. It also shows what type of image the program expects (pre-scaled up or not).

**Comment by alexjc** [comment]
The latest revision (0.2) includes a lot of requested features, but the trained models are not yet as good as 0.1 (still training). I suggest you grab the `v0.1` tag for the moment.

As for input/output examples, it's a good idea! I will add that later.

**Comment by alexjc** [comment]
I uploaded some improved models for 1x enhancing. Try downloading it again from the releases? (I'll let it continue to train overnight, it's not yet converged.)

**Comment by vi** [comment]
With newly downloaded `ne1x-small-0.2.pkl.bz2` it at least doesn't diverge so wildly:

![h_ne1x](https://cloud.githubusercontent.com/assets/173219/20029893/f02a34b6-a369-11e6-90af-8dcfd2148eb5.png)

**Comment by alexjc** [comment]
It's not trained to do iterations, so I don't expect that would be stable. To improve quality, a bigger model is needed — or you can train your own more specialized super-resolution algorithm if you have a specific type of image in mind.

**Comment by vi** [comment]
How many images of some type do I need to get something meaningful? Does it choose model size automatically based on the number of images?

**Comment by alexjc** [comment]
You decide the exact model size by using `--generator-filters=64` (which I call small) or `128` (medium) or `256` (large).  The faces example is trained with approximately 3k images, but with mirroring it's 6k.

**Comment by vi** [comment]
Note: input+model+output example triplets are still expected to be available somewhere (inside or outside Git) to check if neural-enhance is running as expected.

As far as I understand, with appearance of v0.3 version v0.2 is finished (models won't be trained more, code for v0.2 will stay as it is), so input->output test for v0.2 can be added somewhere.

**Comment by alexjc** [comment]
I'll start Issues for each of the models and include examples there.
https://github.com/alexjc/neural-enhance/issues/77
