### ISSUE TITLE
Colours looking bleaker after enhancing

### ISSUE THREAD

**Issue by vi** [alexjc/neural-enhance#52]
Before:

![g](https://cloud.githubusercontent.com/assets/173219/20030153/55cf512e-a370-11e6-8a48-f18bd2f3203a.png)
![r](https://cloud.githubusercontent.com/assets/173219/20030155/59974ece-a370-11e6-9cea-703397342907.png)
![w](https://cloud.githubusercontent.com/assets/173219/20030218/6b9d2994-a371-11e6-8387-7e2cb654eb45.png)
![b](https://cloud.githubusercontent.com/assets/173219/20030220/6f43c724-a371-11e6-9647-fc71c6af2ad5.png)

After:

![g_ne1x](https://cloud.githubusercontent.com/assets/173219/20030162/6223ca90-a370-11e6-8516-407ea11f11fd.png)
![r_ne1x](https://cloud.githubusercontent.com/assets/173219/20030160/6004b9b8-a370-11e6-9ae6-370601c22dfa.png)
![w_ne1x](https://cloud.githubusercontent.com/assets/173219/20030223/72d10488-a371-11e6-9ed0-d8d5e4d5ceeb.png)
![b_ne1x](https://cloud.githubusercontent.com/assets/173219/20030224/77aac228-a371-11e6-8440-e36171f71485.png)

**Comment by alexjc** [comment]
The models available are trained on photos, so extreme whites/blacks or bright colors are not seen often. What types of images are you using? Could train a new model on those for best results, or add histogram matching.

**Comment by vi** [comment]
I tried using it on a screenshot, a snipped from photo, lineart picture.

Colour distorsion look similar in all cases. Especially the green colour.

<pre><a href="http://www.fmwconcepts.com/imagemagick/histmatch/index.php">histmatch</a> -c rgb orig.png orig_ne1x.png postprocessed.png</pre> indeed improces result quality and makes comparison meaningful. If this is a simple operation, it would be useful to have it embedded in neural-enhance.

**Comment by alexjc** [comment]
You're right, I've noticed the extent of the problem. The current models seem to distort all colors, not just the extreme ones. I'll finish training this batch and see what can be done to address it.

**Comment by alexjc** [comment]
Try `v0.3` with `--type=photo --zoom=2` and it should work better. Also, there's now histogram matching with `--rendering-histogram` parameter.
