### ISSUE TITLE
Poor result of enhancement on crisp images

### ISSUE THREAD

**Issue by BanzaiTokyo** [alexjc/neural-enhance#53]
Sorry fr a very vague bug report, I'll be honest - I don't really know what's going on here. Anyway, aa they say - a picture is worth a thousand words, so here's the picture: 
(the comand was simple:  `python enhance.py ./images/celeb1.png` )
![celeb1_ne1x](https://cloud.githubusercontent.com/assets/2467506/20042251/da5412ac-a476-11e6-8cbb-a65a66a29060.png)

**Comment by BanzaiTokyo** [comment]
sorry, this result occured because I didn't update the model. 
Anyway even with the newly downloaded ne1x-small-0.2.pkl.bz2, the result is of significantly lower quality than the original which was not the case with the earlier versions of enhance

**Comment by alexjc** [comment]
The previous iteration does 4x enhancing, it's available as tag `v0.1`.  If this version works better for you, you can roll back for now.  Trying to find a balance of being good at specific images and supporting a wide variety of images.

This new one currently does 1x or 2x by default, so it's fewer pixels.  If you have an example that's better in v0.1, feel free to post the PNG here and I'll take a look.

**Comment by BanzaiTokyo** [comment]
to be specific, here is the original image:
![celeb1](https://cloud.githubusercontent.com/assets/2467506/20055169/2d4fd8ba-a4e0-11e6-8b1b-5ffe52ba9561.png)

and here's its "enhanced" version:
![celeb1_ne1x](https://cloud.githubusercontent.com/assets/2467506/20055185/457407fe-a4e0-11e6-9fb5-0eaee7e54bd4.png)

I think it is quite obvious that there is no enhancement here.

**Comment by alexjc** [comment]
@BanzaiTokyo Yeah, in that case it should try to return a copy of the original image. I'm not sure it can be enhanced at all.

**Comment by eab** [comment]
I tried to enhance some images with v0.1 with the Docker image, the results where amazing.
Later on I tried to build the environment in a Vagrant box to be able to change parameters. I succeeded, but with v0.2 and the new trained datasets I also noticed that the quality of the result is poor.
Hopefully I could invest some time in the next couple days to run the same images against v0.1 and v0.2.

**Comment by alexjc** [comment]
@eab Thanks for the report. The new models work well on blurry and noisy images but perform poorly for plain rescaling of clean images. I will release two different models in the next version.

**Comment by alexjc** [comment]
Try again on `v0.3` with `--type=photo --zoom=2`. If there are new issues feel free to report.
