### ISSUE TITLE
-bash: -1: substring expression < 0

### ISSUE THREAD

**Issue by ianbytchek** [alexjc/neural-enhance#54]
Am I the only one getting this with docker instructions? Using macOS 10.11 and docker machine, tried standard and latest GNU Bash variations. The issue seems to be in `${@:1:-1}` – for some reason it works on pure strings, but not on arguments.

If I get everything correct, in `enhance --zoom=1 --model=small images/example.jpg` example in README the idea with `${@:1:-1}` is to pass `--zoom=1 --model=small`? In which case `${@:1:$#-1}` works.

**Comment by Payuing** [comment]
I have the same issue on MacOS 10.12.1 with `${@:1:-1}`, but after replace it with `${@:1:$#-1}`, it works fine.
Thanks

**Comment by thepanu** [comment]
I had the same issue (Linux) and above mentioned fix did the trick.
