### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by eeric** [alexjc/neural-enhance#56]
python enhance.py --zoom=1 ./images/BAIDU_9.png

  File "enhance.py", line 533
SyntaxError: Non-ASCII character '\xe2' in file enhance.py on line 533, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

python enhance.py ./images/BAIDU_9.png

  File "enhance.py", line 534
    print('↑' if l > average else '↓', end='', flush=True)
                                              ^
SyntaxError: invalid syntax

**Comment by alexjc** [comment]
Use `python3` as indicated in the README!

**Comment by attibalazs** [comment]
had the same issue, got my environments mixed up
