### ISSUE TITLE
Can I supply pairs of picture for training to make it enhance pictures in other way?

### ISSUE THREAD

**Issue by vi** [alexjc/neural-enhance#58]
For example, supply pairs of original and JPEG-degraded pictures to train it to mend JPEG artifacts?

Or is the program inherently scaling-centered and can't be used to revert other transformations?

**Comment by alexjc** [comment]
If you train it with `--train-jpeg=70` it should randomly compress the chunks of input images and learn to fix those. I have not tested this very much yet!

**Comment by alexjc** [comment]
See PR #33 for discussion of adding other features. Hoping to make this extensible somehow.

**Comment by dribnet** [comment]
Hi @vi - I've just updated my `seeds_option` branch referenced in PR #33 to be compatible with the latest tagged release v0.3. So if you'd like to try providing explicit pairs, just use that branch and then use the `--seeds` option to provide a second directory of images to serve as the seeds for the training. Note that the filenames provided in `--train` and `--seeds` are used for matching, there is a routine to compare the lists of files and remove images that don't have a pairing, and the results of this filter/match step are reported prior to training starting.

I'd be curious to see what other people are able to do with this option.
