### ISSUE TITLE
OSError: [Errno 71] Protocol error: '/ns/Users/input_ne1x.png'

### ISSUE THREAD

**Issue by LNFWebsite** [alexjc/neural-enhance#59]
Specs:

```
Windows 8 running Oracle VM VirtualBox
```

I'm failing on `OSError: [Errno 71] Protocol error: '/ns/Users/input_ne1x.png'` after following most of your steps for docker and the partial solution in #43 for shared files between Docker and VirtualBox on Windows.

```
Me@My-Laptop MINGW64 ~
$ docker run -v /c:/ns -it alexjc/neural-enhance /ns/Users/input.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne1x-small-0.2.pkl.bz2` with trained model.

/ns/Users/input.jpg ..Traceback (most recent call last):
  File "enhance.py", line 594, in <module>
    out.save(os.path.splitext(filename)[0]+'_ne%ix.png' % args.zoom)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 1695, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 71] Protocol error: '/ns/Users/input_ne1x.png'

Me@My-Laptop MINGW64 ~
$
```

Is there anything that I'm doing wrong? I appreciate it!

**Comment by LNFWebsite** [comment]
Update:

I've found [this StackOverflow question](http://stackoverflow.com/questions/31756495/ioerror-errno-71-protocol-error-when-reading-a-file-with-python-in-a-virtua) that seems to suggest it might be a permissions issue, but I can't tell.

**Comment by LNFWebsite** [comment]
Also, I have a hunch that I'm missing something about Docker volumes.

Excuse my lack of knowledge on Docker and Virtual Machines, I am a total newbie to this.

**Comment by alexjc** [comment]
I don't know on Windows, but try putting it into `C:\Users\<username\` or a subfolder?

**Comment by LNFWebsite** [comment]
Thanks for getting back to me!

I have placed it in `C:\Users\(myusername)`, but I think the error involves something else. I'll try again...

**Comment by LNFWebsite** [comment]
Thanks for the help! This seems to have been the issue.

Now I'm getting #50 so I guess I have to update the filter library...

**Comment by LNFWebsite** [comment]
@alexjc Quick question, how would I go about updating the filters dataset to `ne2x-large-0.2.pkl.bz2` in Docker?

**Comment by alexjc** [comment]
@LNFWebsite You can edit `docker-cpu.df` and add the large one in, then do `docker build -f docker-cpu.df .`.  To train from the dataset requires a great GPU and 24h.

**Comment by LNFWebsite** [comment]
Ok... Thanks for the reply.

I'm away from my computer, but I'll let you know when I get it up and running.

Thanks for putting the time and effort into this project!

**Comment by LNFWebsite** [comment]
Just a few things to throw out there for other Windows docker users out there, the issue with

```
Error checking context: 'can't stat '\\?\C:\Users\Chris\AppData\Local\Application Data''.
```

Has to do with spaces in the name of a subdirectory of the directory in which you are issuing the `docker build -f docker-cpu.df .` command. Place your `docker-cpu.df` file in a folder of it's own, then cd into that folder and issue the command from there.

**Comment by LNFWebsite** [comment]
@alexjc I finally ran `docker build -f docker-cpu.df .` after adding the large dataset but I am finding two different Docker images being generated, neither of them containing `enhance.py`.

One is named `ubuntu` and the other isn't named. Running them results in a shell within the environment. The unnamed one opens in `/ne` but no files are there (such as enhance.py).

I've tried adding enhance.py manually, but then I get an error saying that the dependencies (`numpy` was the one named) do not exist.

```
Me@My-Laptop MINGW64 ~ $ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED
    SIZE
<none>                  <none>              81c795f85ac9        31 minutes ago
    585.9 MB
alexjc/neural-enhance   latest              cc2a5464e53a        4 days ago
    1.403 GB
ubuntu                  14.04               1e0c3dd64ccd        3 weeks ago
    187.9 MB
```

**Comment by LNFWebsite** [comment]
@alexjc I'm curious, do you know of a way to keep the docker container (neural-enhance) alive even after the `enhance.py` script has ended?

**Comment by alexjc** [comment]
You can try running docker with `--entrypoint /bin/bash` then you can mess around as if it was a regular shell.

**Comment by LNFWebsite** [comment]
@alexjc I'm sure that the manual docker build would have worked now that I know what I'm doing, but the `--entrypoint /bin/bash` solution was the easiest for me.

For the good of everyone else (if they find this on google or something), the commands I used to upgrade the filter dataset to `ne2x-large-0.2.pkl.bz2` were as follows:

Open a new alexjc/neural-enhance container in bash
```
docker run -it --rm -v /c:/ns --entrypoint /bin/bash alexjc/neural-enhance
```

Copy the file from the volume /ns which is the same as drive C:/ (correlated by -v above) (this will only persist for the session of this container)
```
cp /ns/Users/(My User)/ne2x-large-0.2.pkl.bz2 /ne
```

Then run neural-enhance from python directly
```
/opt/conda/bin/python3.5 enhance.py --zoom=2 --model=large /ns/Users/(My User)/input.jpg
```

Thanks for all the help!
