### ISSUE TITLE
Did not work as expected.

### ISSUE THREAD

**Issue by MariasStory** [alexjc/neural-enhance#61]
Hi, I wend through the trouble of installing the 1.5G docker image and was expecting the results that are shown on the github page.
After few tests I see strongly modified images that look like an over saturated sharpening.
What am I doing wrong?

**Comment by MariasStory** [comment]
OK. I think this is related to #50.
Now, I still don't see why you don't provide a fully capable solution.

**Comment by alexjc** [comment]
Building a solution that works for all images as everyone expects is open research. To make a good report, please provide more information and examples (as usual).

**Comment by LNFWebsite** [comment]
@MariasStory Try adding the `--zoom=2` flag to your command and see if you are more satisfied. Otherwise, build with the larger (or older) datasets as discussed in my issue. #59

**Comment by MariasStory** [comment]
Hi @alexjc and @LNFWebsite,
Thanks for your response. I do appreciate your work. I guess I was expecting too much. :-(
I did download the "ne2x-large-0.2.pkl.bz2", but did not try it yet.

**Comment by alexjc** [comment]
@MariasStory I'm training new models for v0.3, will let users select what kind of "enhancement" they want. This should make quality more achievable. If you have an example, post it—that's very useful!

**Comment by alexjc** [comment]
Try again on `v0.3` with `--type=photo --zoom=2`. If there are new issues feel free to report.
