### ISSUE TITLE
v0.1 error--Couldn't find layer `upscale0.3x` in loaded model

### ISSUE THREAD

**Issue by eeric** [alexjc/neural-enhance#65]
Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-small-0.1.pkl.bz2` with trained model.
Traceback (most recent call last):
  File "enhance.py", line 590, in <module>
    enhancer = NeuralEnhancer(loader=False)
  File "enhance.py", line 490, in __init__
    self.model = Model()
  File "enhance.py", line 286, in __init__
    self.load_generator(params)
  File "enhance.py", line 420, in load_generator
    assert k in params, "Couldn't find layer `%s` in loaded model.'" % k
AssertionError: Couldn't find layer `upscale0.3x` in loaded model.'

**Comment by alexjc** [comment]
Ah, you can only use v0.1 models with the code in that tag. The architecture has changed. I'm training new models for v0.3 that should address this.
