### ISSUE TITLE
Pre-trained convolution layers not found

### ISSUE THREAD

**Issue by sashakr** [alexjc/neural-enhance#67]
Hi!
I'm dowloaded pre-trained layers and put them to ../scripts/, close to *.sh file
But neural-enhance didn't found it
What i did wrong?

**Comment by Aneeshers** [comment]
@sashakr  Hi! So put the model in the home directory as a separate file and it should work, like so : 

<img width="646" alt="screen shot 2016-11-09 at 7 14 06 pm" src="https://cloud.githubusercontent.com/assets/23346863/20159755/c034d302-a6b0-11e6-9fe8-254c4a24bfba.png">

**Comment by sashakr** [comment]
@Aneeshers thank you! 
one problem gone:)

**Comment by alexjc** [comment]
Normally the models should go into the directory of the Python file `enhance.py`. I just fixed this...

**Comment by TimeK1LLER** [comment]
Where the dir should be put in?
