### ISSUE TITLE
Docker v0.3 has invalid model url with no arguments

### ISSUE THREAD

**Issue by rlqualls** [alexjc/neural-enhance#71]
Latest docker cpu image needs `--zoom=2` or `--model=repair` to work.

```
ERROR: Model file with pre-trained convolution layers not found. Download it here...
https://github.com/alexjc/neural-enhance/releases/download/v0.3/ne1x-photo-default-0.3.pkl.bz2
```

I feel like the default model type should work with the default zoom.

**Comment by alexjc** [comment]
@rlqualls Agree, defaults should be `--zoom=2` I think.
