### ISSUE TITLE
--rendering-histogram's magenta as out-of-gamut colour

### ISSUE THREAD

**Issue by vi** [alexjc/neural-enhance#73]
I expect `--rendering-histogram` to choose some nearest colour when it can't represent something normally, not magenta.

histmatch's postprocessed result - expected:

![ok](https://cloud.githubusercontent.com/assets/173219/20214640/853740f2-a820-11e6-8fcb-adddcb91387d.png)

`--rendering-histogram`'s result - actual:

![fail](https://cloud.githubusercontent.com/assets/173219/20214656/90120700-a820-11e6-9aed-47c340b97753.png)

**Comment by alexjc** [comment]
Ah, I think it must be missing some clipping then. On line 545 try this:
```
return map_Hb(inv_Ha(A)).clip(0.0, 255.0)
```

**Comment by vi** [comment]
This does not fix the problem. If I try `return map_Hb(inv_Ha(A)).clip(48.0, 96.0)` I see bleak image, but still with magenta as out-of-gamut colour (this magenta also bleakened).

![test](https://cloud.githubusercontent.com/assets/173219/20216001/0ea4a93a-a829-11e6-9de7-46e15487953d.png)

**Comment by alexjc** [comment]
OK, thanks. If it's not this fix below I'll have to dig into it further:
```return map_Hb(inv_Ha(A).clip(0.0, 255.0))```

**Comment by vi** [comment]
This one works.
