### ISSUE TITLE
Getting 'Killed' message on v0.3

### ISSUE THREAD

**Issue by LNFWebsite** [alexjc/neural-enhance#74]
```
root@53d7a6e8e2c2:/ne# /opt/conda/bin/python3.5 enhance.py --zoom=2 /ns/Users/Me/Desktop/Docker/input.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne2x-photo-default-0.3.pkl.bz2` with trained model.

Killed
```

Note that the same command worked fine in v0.2

**Comment by LNFWebsite** [comment]
Also, when running `docker run -it --rm -v /c:/ns alexjc/neural-enhance --zoom=2 /ns/Users/Me/Desktop/Docker/input.jpg`, the script starts and finishes, but the ne2x.png image is nowhere to be found.

**Comment by LNFWebsite** [comment]
Can you possibly use the Docker tags for more specific versioning so that your users can revert to older versions? https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

**Comment by alexjc** [comment]
@LNFWebsite 
- Does the free DockerHub let you make versioned builds via the automated build hook?
- Your command-line looks suspicious, did it work before? Is that folder actually mounted there?

You can build any version easily with this command:
`docker build -f docker-cpu.df .`

As for the `Killed` try typing `--rendering-tile=96` or smaller. LMK!

**Comment by LNFWebsite** [comment]
@alexjc Thanks for replying!

Apparently the `--rendering-tile=96` parameter did the trick! I'm curious however... What does this specify and does it have a negative effect upon the output? Just fooling around I brought the value up to 120 but saw no noticeable difference in the photo (it looked identical to the one with rendering tile at the lower value).

Unfortunately, I couldn't figure out how to use the build hook. I never thought of manually building with the older `docker-cpu.df` Dockerfile. Regardless, all of that would be unnecessary if you version the tags.

> Your command-line looks suspicious, did it work before? Is that folder actually mounted there?

Yeah, it's because I've loaded the image into a shell as you suggested on my last issue so that I can use the larger filter datasets which you provide. For testing this bug, however, I was just using the 2x dataset which loads with v0.3.

I appreciate your repeated help for my issues!

**Comment by LNFWebsite** [comment]
@alexjc BTW... Tried your new website http://enhance.nucl.ai ... Very cool!

http://enhance.nucl.ai/w/dcc64a22-a869-11e6-a3d9-c86000be451f/view

**Comment by alexjc** [comment]
You can also submit new photos on the website too ;-)

When changing the tiles, I think multiples of 16 or 32 will be faster but I haven't checked this yet.  The new defaults will be `--rendering=tile=80` and `--rendering-padding=24`. This should not affect the results visibly, it's the same computation but run on different tiles in the image, then combined together.

**Comment by LNFWebsite** [comment]
Okay... Thanks for fixing this! Keep up the good work!
