### ISSUE TITLE
how to run def add_to_buffer(self, f):

### ISSUE THREAD

**Issue by eeric** [alexjc/neural-enhance#81]
order: 
--python3 -m pdb enhance.py --train images/*.jpg --train-blur=1
... ...
Training 10 epochs on random image sections with batch size 15.
  - 44 tensors learned for generator.
  - 21 tensors learned for discriminator.
so, the performence was stopped.
why?
how to run def add_to_buffer(self, f):?

**Comment by alexjc** [comment]
Use the scripts in `train/` as a reference. You may need to quote the parameter to `--train`.

**Comment by eeric** [comment]
How to run function def add_to_buffer(self, f): if using correct order?

**Comment by alexjc** [comment]
I don't understand what you mean. If you run with `-m pdb` then it might be very slow, I don't think it stopped.

**Comment by eeric** [comment]
”-m pdb“ means step through every statement in the program.
So if your code is implemented successfully, how to run add_to_buffer(self, f) function, that is that it doesn't work to add_to_buffer(self, f) function.

**Comment by alexjc** [comment]
Check how the function is called just below? I think it takes a filename. Using a good debugger (e.g. PyCharm or Visual Studio Code) will help you see the exact values used.
