### ISSUE TITLE
About the demo

### ISSUE THREAD

**Issue by hitjingxuan** [alexjc/neural-enhance#82]
The low pixels picture is: 
![test](https://cloud.githubusercontent.com/assets/12457112/20305418/7cf7597e-ab70-11e6-9bf6-553d16881316.png)

Whenever I run the model(v0.3) with parameters "--model=repair --zoom=1 " OR "--model=default --zoom=2", 
Why the result is not so good as what you had shown in examples?  Should I change other parameters?

Thx

**Comment by alexjc** [comment]
The faces example is a custom model trained on faces only, as explained in the description just below. See Issue #21.

**Comment by hitjingxuan** [comment]
But when I try the other example pictures as you showed, it still enhance little. Hardly find the different except the size and more bright.

What the version and model it is when you try those example pictures?

**Comment by alexjc** [comment]
The online demo runs on the 4x model from `v0.1`, those are in the README.  The ones from GitHub issues are from `v0.3` with the command-lines specified.

If you compare in an image editing program, the results are noticeably better than filters like Lanczos.

**Comment by AlexeyKruglov** [comment]
v0.2 2x network seems to work much better than the current v0.3 2x network. But it requires the older revision of the code to work. Try checking out commit de047d7 (run: git checkout de047).

**Comment by hitjingxuan** [comment]
> alexjc:
EDIT: You should also use actual low-resolution images, not artificially pixelated images like the face above. It's just used to illustrate the input at the same size as output for the README.

I know where I was wrong. Just as alexjc said, I choose the wrong input when test. The result is correct now.

Thx again.

**Comment by alexjc** [comment]
> v0.2 2x network seems to work much better than the current v0.3 2x network. But it requires the
> older revision of the code to work. Try checking out commit de047d6 (run: git checkout de047).

In some cases this is true (if the image matches the blur-centric settings used for training), but I found 0.3 to be generally more suitable. There's another thread with comparison about 0.2.

**Comment by aezco** [comment]
What about older faces for wrinkles? does it smooth or are the results perfect?
