### ISSUE TITLE
ERROR: Model file with pre-trained convolution layers not found. Download it here... 

### ISSUE THREAD

**Issue by unxed** [alexjc/neural-enhance#83]
Installed in docker (under linux mint 18) as described in readme. Not very familar with docker. How to put downloaded dataset into the docker's volume so neural-enhance can see it?

Thanks.

**Comment by unxed** [comment]
managed to run neural-enhance without docker.

consider adding "sudo apt-get install python3-dev" and "pip install wheel" into the manual installation howto.

**Comment by alexjc** [comment]
OK, glad you found it.

**Comment by fchouteau** [comment]
Hi,
I am trying to do the same thing without installing locally, how can you specify the path to local weights in the docker image ? (for zoom 4x)
Regards,

**Comment by unxed** [comment]
fchouteau, btw, how do you write files into the docker image (and where is it located by default)?
thanks!

**Comment by fchouteau** [comment]
I rewrote the dockerfile to pull the weights during docker build.

The current dockerfile is only meant for a temporary run as it specifies enhance.py as an entry point. If you want to run an interactive docker delete this entry point (you can then wget on the directory for the weights).
See my pull request for adding 4x weights during docker build.

**Comment by alexjc** [comment]
@unxed You can use `--entrypoint /bin/bash` as command to docker to run a shell inside. It's located in `/ne`.

**Comment by unxed** [comment]
alexjc, thanks for the answer (and for this amazing tool :)

**Comment by omidraha** [comment]
```

This [file](https://github.com/alexjc/neural-enhance/releases/download/v0.3/ne5x-photo-repair-0.3.pkl.bz2) is not exist.

root@ff59ea4afe96:/ne# wget https://github.com/alexjc/neural-enhance/releases/download/v0.3/ne5x-photo-repair-0.3.pkl.bz2
--2018-01-09 17:23:18--  https://github.com/alexjc/neural-enhance/releases/download/v0.3/ne5x-photo-repair-0.3.pkl.bz2
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-09 17:23:21 ERROR 404: Not Found.

```
