### ISSUE TITLE
Using spark

### ISSUE THREAD

**Issue by cali1** [alexjc/neural-enhance#88]
Can spark be used to speed up training and processing?

**Comment by Sabahate123** [comment]
Please stop emailing me
Sent from my iPhone

On 16 Nov 2016, at 21:39, cali1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Can spark be used to speed up training and processing?

**Comment by alexjc** [comment]
@cali1 No, it needs to be a deep learning framework to speed up the training. Processing can be sped up by lowering the quality.
