### ISSUE TITLE
What's means to ['total', 'prcpt', 'smthn', 'advrs']?

### ISSUE THREAD

**Issue by eeric** [alexjc/neural-enhance#89]
During the training,  it is implemented to sentence print('  - generator {}'.format(' '.join(gen_info))), and What's means to ['total', 'prcpt', 'smthn', 'advrs'], respectively?

**Comment by alexjc** [comment]
They are values for the losses, see the `loss_*()` functions. Explanations here: http://arxiv.org/abs/1609.04802
