### ISSUE TITLE
It occurs stagnation to the training, why? 

### ISSUE THREAD

**Issue by eeric** [alexjc/neural-enhance#96]
It occurs stagnation to the training over 30 hours on 160 thousands samples, why? 
The detail training, following:

 - Using the device `gpu0` for neural computation.

Training 100 epochs on random image sections with batch size 15.
  - Loaded file `ne2x-photo-face-0.3.pkl.bz2` with trained model.
  - 38 tensors learned for generator.
  - 21 tensors learned for discriminator.
....waiting forever

**Comment by alexjc** [comment]
Just applying super-resolution works? Have you used CUDA on your machine before?

Try CTRL+C to interrupt the code and see if it's stuck. Use a debugger to find out where it struggles.

**Comment by eeric** [comment]
ok, the problem is solved, the reason that the value of batch-shape is a little big.

**Comment by dlongry** [comment]
I met the same issue  but I usig the parameter --batch-shape=xxx（smaller）, it doesn't work.so do you have other ways to go train code？I'm also waiting forever..... @eeric @alexjc
