### ISSUE TITLE
The value of discriminator hovers between  0.57 to 0.71 by script provided

### ISSUE THREAD

**Issue by eeric** [alexjc/neural-enhance#98]
The script is following,
python3.4 enhance.py \
    --train "$OPEN_IMAGES_PATH/*/*.jpg" --type photo --model default \
    --epochs=500 --batch-shape=240 --device=gpu0 \
    --generator-downscale=0 --generator-upscale=1 .....
so, the value of discriminator hovers between  0.57 to 0.71 by script provided, why?

**Comment by alexjc** [comment]
The discriminator value will hover forever as it trains against the generator. That's a measure of successful it is at detecting real from fake.

**Comment by eeric** [comment]
Ok, but The discriminator value cann't reach more than 0.9, however, it can to 1X script provided.
How to improve the discriminator value?

**Comment by alexjc** [comment]
Maximum is 1.0, but you probably don't benefit from it being that high. You can increase `--discriminator-size` in training script.

**Comment by eeric** [comment]
Try on it, thanks!
