### ISSUE TITLE
docker image not start

### ISSUE THREAD

**Issue by xeonvs** [alexjc/neural-enhance#99]
Hi!
I try to run but this error is produced
```
# docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance /bin/bash
/opt/conda/bin/python3.5: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
jail: /opt/conda/bin/python3.5 enhance.py --device=cpu /bin/bash: failed
```

**Comment by alexjc** [comment]
Are you running the latest Docker? The currently live container works fine, you should get:
```OSError: cannot identify image file '/bin/bash'```

Or better, run this to show help:
```docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance --help```

**Comment by xeonvs** [comment]
Sorry! /bin/bash uncorrectly copy-paste
same error on any command

docker run --rm -v `pwd`:/ne/input -it alexjc/neural-enhance --help
/opt/conda/bin/python3.5: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
jail: /opt/conda/bin/python3.5 enhance.py --device=cpu --help: failed

docker --version
Docker version 1.7.0-dev, build 582db78

**Comment by alexjc** [comment]
I have ```Docker version 1.12.3, build 6b644ec, experimental```. You could also try deleting images if you don't want to upgrade. Docker is notoriously fragile with versioning and backwards compatibility.
